import { structures as landmarks } from './data.js';

const bilateral = (names) => names.flatMap((n) => ['Right ' + n, 'Left ' + n]);
const bones = [
  'Frontal bone',
  'Occipital bone',
  'Sphenoid bone',
  'Ethmoid bone',
  'Right parietal bone',
  'Left parietal bone',
  'Right temporal bone',
  'Left temporal bone',
  'Mandible',
  'Vomer',
  'Right maxilla',
  'Left maxilla',
  'Right zygomatic bone',
  'Left zygomatic bone',
  'Right nasal bone',
  'Left nasal bone',
  'Right lacrimal bone',
  'Left lacrimal bone',
  'Right palatine bone',
  'Left palatine bone',
  'Right inferior nasal concha',
  'Left inferior nasal concha',
  'Hyoid bone',
  ...bilateral(['malleus', 'incus', 'stapes']),
  ...Array.from({ length: 7 }, (_, i) => 'C' + (i + 1) + ' cervical vertebra'),
  ...Array.from({ length: 12 }, (_, i) => 'T' + (i + 1) + ' thoracic vertebra'),
  ...Array.from({ length: 5 }, (_, i) => 'L' + (i + 1) + ' lumbar vertebra'),
  'Sacrum',
  'Coccyx',
  'Sternum',
  ...Array.from({ length: 12 }, (_, i) => bilateral(['rib ' + (i + 1)])).flat(),
  'Right hip bone',
  'Left hip bone',
  ...bilateral(['clavicle', 'scapula', 'humerus', 'radius', 'ulna']),
  ...bilateral([
    'scaphoid',
    'lunate',
    'triquetrum',
    'pisiform',
    'trapezium',
    'trapezoid',
    'capitate',
    'hamate',
  ]),
  ...Array.from({ length: 5 }, (_, i) => bilateral(['metacarpal ' + (i + 1)])).flat(),
  ...Array.from({ length: 14 }, (_, i) => bilateral(['hand phalanx ' + (i + 1)])).flat(),
  ...bilateral(['femur', 'patella', 'tibia', 'fibula']),
  ...bilateral([
    'talus',
    'calcaneus',
    'navicular',
    'cuboid',
    'medial cuneiform',
    'intermediate cuneiform',
    'lateral cuneiform',
  ]),
  ...Array.from({ length: 5 }, (_, i) => bilateral(['metatarsal ' + (i + 1)])).flat(),
  ...Array.from({ length: 14 }, (_, i) => bilateral(['foot phalanx ' + (i + 1)])).flat(),
];
const muscleBases = [
  'Frontalis',
  'Occipitalis',
  'Temporalis',
  'Masseter',
  'Orbicularis oculi',
  'Orbicularis oris',
  'Sternocleidomastoid',
  'Scalenes',
  'Trapezius',
  'Deltoid',
  'Pectoralis major',
  'Pectoralis minor',
  'Serratus anterior',
  'Latissimus dorsi',
  'Rhomboid major',
  'Supraspinatus',
  'Infraspinatus',
  'Teres minor',
  'Teres major',
  'Subscapularis',
  'Biceps brachii',
  'Brachialis',
  'Triceps brachii',
  'Brachioradialis',
  'Pronator teres',
  'Flexor carpi radialis',
  'Palmaris longus',
  'Flexor carpi ulnaris',
  'Extensor carpi radialis longus',
  'Extensor carpi radialis brevis',
  'Extensor digitorum of hand',
  'Extensor carpi ulnaris',
  'Rectus abdominis',
  'External oblique',
  'Internal oblique',
  'Transversus abdominis',
  'Diaphragm',
  'Intercostals',
  'Iliopsoas',
  'Gluteus maximus',
  'Gluteus medius',
  'Gluteus minimus',
  'Tensor fasciae latae',
  'Adductor longus',
  'Adductor magnus',
  'Gracilis',
  'Sartorius',
  'Rectus femoris',
  'Vastus lateralis',
  'Vastus medialis',
  'Vastus intermedius',
  'Biceps femoris',
  'Semitendinosus',
  'Semimembranosus',
  'Tibialis anterior',
  'Fibularis longus',
  'Gastrocnemius',
  'Soleus',
  'Tibialis posterior',
  'Flexor digitorum longus',
  'Extensor digitorum longus',
];
const group = {
  organs: [
    'Oral cavity',
    'Tongue',
    'Teeth',
    'Hard palate',
    'Soft palate',
    'Parotid gland',
    'Submandibular gland',
    'Sublingual gland',
    'Pharynx',
    'Larynx',
    'Trachea',
    'Esophagus',
    'Thymus',
    'Heart',
    'Right lung',
    'Left lung',
    'Pleura',
    'Liver',
    'Gallbladder',
    'Stomach',
    'Spleen',
    'Pancreas',
    'Duodenum',
    'Jejunum',
    'Ileum',
    'Cecum',
    'Appendix',
    'Ascending colon',
    'Transverse colon',
    'Descending colon',
    'Sigmoid colon',
    'Rectum',
    'Right kidney',
    'Left kidney',
    'Right ureter',
    'Left ureter',
    'Urinary bladder',
    'Urethra',
    'Peritoneum',
    'Greater omentum',
    'Mesentery',
  ],
  digestive: [
    'Pyloric sphincter',
    'Lower esophageal sphincter',
    'Hepatic duct',
    'Common bile duct',
    'Pancreatic duct',
    'Hepatic portal vein',
    'Ileocecal valve',
    'Anal canal',
  ],
  respiratory: [
    'Right upper lobe bronchus',
    'Right middle lobe bronchus',
    'Right lower lobe bronchus',
    'Left upper lobe bronchus',
    'Left lower lobe bronchus',
    'Carina',
    'Epiglottis',
    'Nasal cavity',
    'Nasopharynx',
    'Oropharynx',
    'Alveolar sacs',
  ],
  urinary: [
    'Right kidney cortex',
    'Right kidney medulla',
    'Left kidney cortex',
    'Left kidney medulla',
    'Right renal pelvis',
    'Left renal pelvis',
    'Bladder trigone',
    'Renal corpuscles',
  ],
  reproductive: [
    'Right ovary',
    'Left ovary',
    'Right uterine tube',
    'Left uterine tube',
    'Uterus',
    'Cervix',
    'Vagina',
    'Vulva',
    'Right testis',
    'Left testis',
    'Epididymis',
    'Ductus deferens',
    'Seminal vesicle',
    'Prostate',
    'Bulbourethral gland',
    'Penis',
    'Scrotum',
  ],
  endocrine: [
    'Hypothalamus',
    'Anterior pituitary',
    'Posterior pituitary',
    'Pineal gland',
    'Right parathyroid gland',
    'Left parathyroid gland',
    'Right adrenal cortex',
    'Left adrenal cortex',
    'Adrenal medulla',
    'Pancreatic islets',
  ],
  sensory: [
    'Right eyeball',
    'Left eyeball',
    'Cornea',
    'Lens',
    'Retina',
    'Right cochlea',
    'Left cochlea',
    'Right vestibular apparatus',
    'Left vestibular apparatus',
    'Right optic nerve',
    'Left optic nerve',
    'Olfactory bulbs',
  ],
  immune: [
    'Right tonsil',
    'Left tonsil',
    'Right cervical lymph nodes',
    'Left cervical lymph nodes',
    'Right axillary lymph nodes',
    'Left axillary lymph nodes',
    'Right hilar lymph nodes',
    'Left hilar lymph nodes',
    'Mediastinal lymph nodes',
    'Cisterna chyli',
    'Thoracic duct',
    'Right lymphatic duct',
    'Mesenteric lymph nodes',
    'Preaortic lymph nodes',
    'Right iliac lymph nodes',
    'Left iliac lymph nodes',
    'Right inguinal lymph nodes',
    'Left inguinal lymph nodes',
    'Right popliteal lymph nodes',
    'Left popliteal lymph nodes',
    'Lymphatic lacteals',
  ],
  joints: [
    'Temporomandibular joint',
    'Atlanto-occipital joint',
    'Intervertebral discs',
    'Sternoclavicular joints',
    'Costochondral joints',
    'Right shoulder joint',
    'Left shoulder joint',
    'Right elbow joint',
    'Left elbow joint',
    'Right wrist joint',
    'Left wrist joint',
    'Sacroiliac joints',
    'Pubic symphysis',
    'Right hip joint',
    'Left hip joint',
    'Right knee joint',
    'Left knee joint',
    'Right ankle joint',
    'Left ankle joint',
    'Right rotator cuff',
    'Left rotator cuff',
    'Right cruciate ligaments',
    'Left cruciate ligaments',
    'Achilles tendons',
  ],
  skin: [
    'Scalp',
    'Forehead',
    'Right auricle',
    'Left auricle',
    'Anterior neck',
    'Right pectoral region',
    'Left pectoral region',
    'Abdominal wall',
    'Umbilicus',
    'Right axilla',
    'Left axilla',
    'Right palm',
    'Left palm',
    'Right anterior thigh',
    'Left anterior thigh',
    'Nails',
    'Hair follicles',
    'Sebaceous glands',
    'Sweat glands',
  ],
};
const routes = {
  arteries: [
    'Aortic arch',
    'Ascending aorta',
    'Descending thoracic aorta',
    'Abdominal aorta',
    'Right brachiocephalic trunk',
    'Right subclavian artery',
    'Left subclavian artery',
    'Right axillary artery',
    'Left axillary artery',
    'Right brachial artery',
    'Left brachial artery',
    'Right radial artery',
    'Left radial artery',
    'Right ulnar artery',
    'Left ulnar artery',
    'Right common carotid artery',
    'Left common carotid artery',
    'Right internal carotid artery',
    'Left internal carotid artery',
    'Right external carotid artery',
    'Left external carotid artery',
    'Right vertebral artery',
    'Left vertebral artery',
    'Basilar artery',
    'Anterior cerebral arteries',
    'Middle cerebral arteries',
    'Pulmonary trunk',
    'Right pulmonary artery',
    'Left pulmonary artery',
    'Right coronary artery',
    'Left coronary artery',
    'Celiac trunk',
    'Common hepatic artery',
    'Splenic artery',
    'Superior mesenteric artery',
    'Inferior mesenteric artery',
    'Right renal artery',
    'Left renal artery',
    'Right common iliac artery',
    'Left common iliac artery',
    'Right internal iliac artery',
    'Left internal iliac artery',
    'Right external iliac artery',
    'Left external iliac artery',
    'Right profunda femoris artery',
    'Left profunda femoris artery',
    'Right femoral artery',
    'Left femoral artery',
    'Right popliteal artery',
    'Left popliteal artery',
    'Anterior tibial arteries',
    'Posterior tibial arteries',
    'Dorsalis pedis arteries',
  ],
  veins: [
    'Superior vena cava',
    'Inferior vena cava',
    'Right subclavian vein',
    'Left subclavian vein',
    'Right axillary vein',
    'Left axillary vein',
    'Right cephalic vein',
    'Left cephalic vein',
    'Right basilic vein',
    'Left basilic vein',
    'Right brachial veins',
    'Left brachial veins',
    'Right internal jugular vein',
    'Left internal jugular vein',
    'Right external jugular vein',
    'Left external jugular vein',
    'Right brachiocephalic vein',
    'Left brachiocephalic vein',
    'Azygos vein',
    'Pulmonary veins',
    'Hepatic veins',
    'Hepatic portal vein',
    'Superior mesenteric vein',
    'Inferior mesenteric vein',
    'Right renal vein',
    'Left renal vein',
    'Right common iliac vein',
    'Left common iliac vein',
    'Right external iliac vein',
    'Left external iliac vein',
    'Right great saphenous vein',
    'Left great saphenous vein',
    'Right femoral vein',
    'Left femoral vein',
    'Right popliteal vein',
    'Left popliteal vein',
    'Tibial veins',
  ],
  nerves: [
    'Olfactory nerves',
    'Optic chiasm',
    'Oculomotor nerves',
    'Trochlear nerves',
    'Trigeminal nerves',
    'Abducens nerves',
    'Facial nerves',
    'Vestibulocochlear nerves',
    'Glossopharyngeal nerves',
    'Vagus nerves',
    'Accessory nerves',
    'Hypoglossal nerves',
    'Cervical plexuses',
    'Right phrenic nerve',
    'Left phrenic nerve',
    'Right brachial plexus',
    'Left brachial plexus',
    'Median nerves',
    'Ulnar nerves',
    'Radial nerves',
    'Musculocutaneous nerves',
    'Femoral nerves',
    'Obturator nerves',
    'Lumbar plexuses',
    'Sacral plexuses',
    'Right sciatic nerve',
    'Left sciatic nerve',
    'Tibial nerves',
    'Common fibular nerves',
    'Superficial fibular nerves',
    'Deep fibular nerves',
    'Intercostal nerves',
    'Sympathetic trunks',
    'Enteric plexuses',
  ],
  lymph: [
    'Submandibular lymph nodes',
    'Right cervical lymph node chain',
    'Left cervical lymph node chain',
    'Right supraclavicular lymph nodes',
    'Left supraclavicular lymph nodes',
    'Right axillary lymph nodes',
    'Left axillary lymph nodes',
    'Right epitrochlear lymph nodes',
    'Left epitrochlear lymph nodes',
    'Right hilar lymph nodes',
    'Left hilar lymph nodes',
    'Mediastinal lymph nodes',
    'Cisterna chyli',
    'Thoracic duct',
    'Right lymphatic duct',
    'Mesenteric lymph nodes',
    'Preaortic lymph nodes',
    'Right lumbar lymph nodes',
    'Left lumbar lymph nodes',
    'Right iliac lymph nodes',
    'Left iliac lymph nodes',
    'Right inguinal lymph nodes',
    'Left inguinal lymph nodes',
    'Right popliteal lymph nodes',
    'Left popliteal lymph nodes',
    'Lymphatic lacteals',
  ],
};
function region(name) {
  if (
    /brain|skull|face|ear|eye|nose|mouth|cranial|cervical|temporal|frontal|occipital|parietal|sphenoid|ethmoid|mandible|maxilla|zygomatic|nasal|lacrimal|palatine|hyoid|stapes|incus|malleus|olfactory|optic|retina|lens/.test(
      name.toLowerCase(),
    )
  )
    return 'head';
  if (
    /hand|carpal|metacarpal|clavicle|scapula|humerus|radius|ulna|rib|sternum|thorac|lung|heart|shoulder|arm|pectoral|brachial|trachea|larynx|thymus|chest/.test(
      name.toLowerCase(),
    )
  )
    return 'chest';
  if (
    /hip|pelvis|sacrum|coccyx|bladder|uter|ovary|prostate|urethra|rect|anal|pubic|inguinal|genital|testis|vagina/.test(
      name.toLowerCase(),
    )
  )
    return 'pelvis';
  if (
    /femur|patella|tibia|fibula|tars|talus|calcane|metatars|foot|ankle|sole|glute|femor|hamstring|calf|gastrocnemius|sciatic|popliteal|leg/.test(
      name.toLowerCase(),
    )
  )
    return 'legs';
  if (
    /colon|intestin|gastric|duoden|jejun|ileum|kidney|renal|liver|pancrea|spleen|adrenal|lumbar|abdom|gallbladder|mesenter|hepatic/.test(
      name.toLowerCase(),
    )
  )
    return 'abdomen';
  return 'chest';
}
function location(name, r) {
  const side = /^Right /.test(name)
    ? 'Patient right'
    : /^Left /.test(name)
      ? 'Patient left'
      : 'Midline or paired';
  return r[0].toUpperCase() + r.slice(1) + ' · ' + side;
}
const all = [...landmarks];
const seen = new Set(landmarks.map((s) => s.id));
function insert(name, system, index = 0) {
  const id =
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') +
    '-' +
    system;
  if (seen.has(id)) return;
  seen.add(id);
  const r = region(name),
    side = /^Right /.test(name) ? -1 : /^Left /.test(name) ? 1 : 0;
  const cy = { head: 130, chest: 285, abdomen: 420, pelvis: 550, legs: 700 }[r];
  let x =
    380 +
    side *
      (r === 'head' ? 22 : r === 'chest' ? 38 : r === 'abdomen' ? 43 : r === 'pelvis' ? 31 : 48);
  if (!side) x += ((index % 7) - 3) * 4;
  if (system === 'bones' && /vertebra|rib/.test(name.toLowerCase())) x += ((index % 3) - 1) * 5;
  const hue = {
    bones: 'bone',
    muscles: 'muscle',
    arteries: 'artery',
    veins: 'vein',
    nerves: 'nerve',
    lymph: 'lymph',
  }[system];
  all.push({
    id,
    name,
    system,
    region: r,
    x,
    y: cy + ((index % 5) - 2) * 4,
    z: system === 'bones' ? 0 : 1,
    size: 13,
    kind: hue || system,
    city: name + ' district',
    role: name + ' · ' + system + ' system',
    location: location(name, r),
    connection: 'Anatomically located alongside related ' + r + ' structures.',
    memory: name + ' is mapped to its anatomical position in the body city.',
    fact: name + ' is included in the whole-body gross-anatomy atlas.',
  });
}
bones.forEach((n, i) => insert(n, 'bones', i));
const centralMuscles = [
  'Diaphragm',
  'Intercostals',
  'Rectus abdominis',
  'External oblique',
  'Internal oblique',
  'Transversus abdominis',
  'Frontalis',
  'Occipitalis',
  'Temporalis',
  'Masseter',
  'Sartorius',
  'Iliopsoas',
];
centralMuscles.forEach((n, i) => insert(n, 'muscles', i));
muscleBases
  .filter((n) => !centralMuscles.includes(n))
  .forEach((n, i) =>
    bilateral([n.toLowerCase()]).forEach((side, j) => insert(side, 'muscles', i * 2 + j)),
  );
for (const [system, names] of Object.entries(group)) names.forEach((n, i) => insert(n, system, i));
for (const [system, names] of Object.entries(routes)) names.forEach((n, i) => insert(n, system, i));
export const systems = [
  { id: 'organs', name: 'Organs & viscera', color: '#cf6d5c', kind: 'organ' },
  { id: 'bones', name: 'Skeleton · all 206 bones', color: '#ded0a4', kind: 'bone' },
  { id: 'muscles', name: 'Skeletal muscles', color: '#c45863', kind: 'muscle' },
  { id: 'arteries', name: 'Arteries', color: '#e46257', kind: 'artery' },
  { id: 'veins', name: 'Veins', color: '#669ad0', kind: 'vein' },
  { id: 'nerves', name: 'Nerves & plexuses', color: '#e8be5e', kind: 'nerve' },
  { id: 'lymph', name: 'Lymph, vessels & nodes', color: '#75b98b', kind: 'lymph' },
  { id: 'digestive', name: 'Digestive system', color: '#dda161', kind: 'organ' },
  { id: 'respiratory', name: 'Respiratory system', color: '#72b6c2', kind: 'organ' },
  { id: 'urinary', name: 'Urinary system', color: '#b496d2', kind: 'organ' },
  { id: 'reproductive', name: 'Reproductive anatomy', color: '#d88fa7', kind: 'organ' },
  { id: 'endocrine', name: 'Endocrine system', color: '#e3bd75', kind: 'organ' },
  { id: 'sensory', name: 'Senses & cranial nerves', color: '#87b5d5', kind: 'organ' },
  {
    id: 'joints',
    name: 'Joints & connective tissue',
    color: '#aaaE9a'.toLowerCase(),
    kind: 'bone',
  },
  { id: 'skin', name: 'Integument & surface landmarks', color: '#dfbcae', kind: 'organ' },
  { id: 'immune', name: 'Immune & lymphatic organs', color: '#77b68b', kind: 'organ' },
];
export const structures = all;
export const regions = [
  { id: 'all', name: 'Whole body' },
  { id: 'head', name: 'Head & neck' },
  { id: 'chest', name: 'Thorax' },
  { id: 'abdomen', name: 'Abdomen' },
  { id: 'pelvis', name: 'Pelvis' },
  { id: 'legs', name: 'Lower limbs' },
];
