export const systems = [
  { id: 'organs', name: 'Organs', subtitle: 'The essential landmarks', color: '#bf7867' },
  { id: 'arteries', name: 'Arteries', subtitle: 'Blood away from the heart', color: '#c65252' },
  { id: 'veins', name: 'Veins', subtitle: 'Blood toward the heart', color: '#537fb4' },
  { id: 'nerves', name: 'Nerves', subtitle: 'Signals & sensation', color: '#b58b37' },
  { id: 'lymph', name: 'Lymphatics', subtitle: 'Drainage & immune defense', color: '#6b9774' },
];
export const structures = [
  {
    id: 'brain',
    name: 'Brain',
    system: 'organs',
    region: 'head',
    x: 380,
    y: 94,
    city: 'Central command',
    role: 'Coordinates movement, sensation, thought, memory, and many processes that keep you alive.',
    location: 'Within the cranial cavity, protected by the skull and meninges.',
    connection: 'The brain communicates with the body through the spinal cord and cranial nerves.',
    memory:
      'Think of a city hall and control center: decisions and incoming information meet here.',
    fact: 'The cerebellum helps coordinate balance and movement; the brainstem regulates vital functions such as breathing.',
    size: 45,
  },
  {
    id: 'thyroid',
    name: 'Thyroid gland',
    system: 'organs',
    region: 'head',
    x: 380,
    y: 189,
    city: 'Energy regulation office',
    role: 'Produces thyroid hormones that help regulate metabolism, growth, and development.',
    location:
      'In the anterior neck, just below the larynx, with lobes on either side of the trachea.',
    connection:
      'Hormone release is regulated by the hypothalamus and pituitary through feedback loops.',
    memory: 'An energy office changes the pace of work throughout the city.',
    fact: 'Its two lobes are connected by a narrow isthmus.',
    size: 23,
  },
  {
    id: 'right-lung',
    name: 'Right lung',
    system: 'organs',
    region: 'chest',
    x: 326,
    y: 270,
    city: 'Right air-exchange station',
    role: 'Exchanges oxygen and carbon dioxide between air in the alveoli and blood in pulmonary capillaries.',
    location:
      'In the right side of the thorax. In an anterior view, the patient’s right is on your left.',
    connection:
      'Receives blood from the pulmonary arteries and returns it through the pulmonary veins.',
    memory: 'An air-exchange station supplies fresh oxygen and removes carbon dioxide.',
    fact: 'The right lung has three lobes; the left lung has two.',
    size: 37,
  },
  {
    id: 'left-lung',
    name: 'Left lung',
    system: 'organs',
    region: 'chest',
    x: 433,
    y: 268,
    city: 'Left air-exchange station',
    role: 'Exchanges gases across the thin alveolar-capillary membrane.',
    location:
      'In the left side of the thorax, beside the heart. Its cardiac notch accommodates the heart.',
    connection: 'Connected to the trachea by the left main bronchus.',
    memory: 'The smaller partner station makes room for the central pump.',
    fact: 'The left lung is divided into superior and inferior lobes.',
    size: 33,
  },
  {
    id: 'heart',
    name: 'Heart',
    system: 'organs',
    region: 'chest',
    x: 386,
    y: 307,
    city: 'Central pumping station',
    role: 'A muscular pump that keeps blood moving through the pulmonary and systemic circuits.',
    location:
      'In the middle mediastinum, between the lungs, behind the sternum. Most of it lies left of the midline.',
    connection:
      'The right side sends blood to the lungs. The left side sends oxygenated blood to the body through the aorta.',
    memory:
      'One station, two pumps. The right pump serves the lungs; the left pump serves the rest of the city.',
    fact: 'Four chambers, four valves, and two connected circuits keep blood moving in one direction.',
    size: 29,
  },
  {
    id: 'liver',
    name: 'Liver',
    system: 'organs',
    region: 'abdomen',
    x: 332,
    y: 375,
    city: 'Processing & distribution center',
    role: 'Processes nutrients, makes bile and plasma proteins, stores glycogen, and metabolizes many substances.',
    location: 'Mostly in the right upper abdomen, immediately below the diaphragm.',
    connection:
      'Receives nutrient-rich blood through the portal vein and oxygenated blood through the hepatic artery.',
    memory:
      'A processing center sorts incoming goods, stores supplies, and handles chemical waste.',
    fact: 'Bile is made by the liver and stored and concentrated in the gallbladder.',
    size: 43,
  },
  {
    id: 'stomach',
    name: 'Stomach',
    system: 'organs',
    region: 'abdomen',
    x: 415,
    y: 384,
    city: 'Food preparation plant',
    role: 'Stores and mixes food with acid and enzymes, beginning substantial protein digestion.',
    location: 'In the left upper abdomen, between the esophagus and duodenum.',
    connection: 'Delivers partially digested food, called chyme, into the small intestine.',
    memory: 'A preparation plant breaks large deliveries into material the city can process.',
    fact: 'Most nutrient absorption takes place farther along, in the small intestine.',
    size: 28,
  },
  {
    id: 'spleen',
    name: 'Spleen',
    system: 'organs',
    region: 'abdomen',
    x: 455,
    y: 378,
    city: 'Blood inspection center',
    role: 'Filters blood, recycles aging red blood cells, and supports immune responses.',
    location: 'In the left upper abdomen, posterolateral to the stomach, beneath ribs 9–11.',
    connection: 'Unlike a lymph node, the spleen filters blood rather than lymph.',
    memory: 'An inspection center checks circulating cargo and recycles worn-out vehicles.',
    fact: 'The spleen is a lymphoid organ but does not filter lymph.',
    size: 18,
  },
  {
    id: 'gallbladder',
    name: 'Gallbladder',
    system: 'organs',
    region: 'abdomen',
    x: 343,
    y: 402,
    city: 'Bile storage depot',
    role: 'Stores and concentrates bile, releasing it to help digest fats.',
    location: 'On the inferior surface of the liver, in the right upper abdomen.',
    connection: 'The biliary ducts carry bile to the duodenum.',
    memory: 'A small storage depot beside the processing center releases supplies when needed.',
    fact: 'Bile helps emulsify fats; it is not a digestive enzyme.',
    size: 15,
  },
  {
    id: 'pancreas',
    name: 'Pancreas',
    system: 'organs',
    region: 'abdomen',
    x: 398,
    y: 421,
    city: 'Enzyme & glucose control plant',
    role: 'Produces digestive enzymes and hormones, including insulin and glucagon, that regulate blood glucose.',
    location: 'Across the posterior upper abdomen, mostly behind the stomach.',
    connection: 'Its digestive secretions enter the duodenum through the pancreatic duct.',
    memory: 'A dual-purpose factory supplies digestion and regulates the city’s fuel balance.',
    fact: 'The pancreatic head sits within the curve of the duodenum.',
    size: 24,
  },
  {
    id: 'right-kidney',
    name: 'Right kidney',
    system: 'organs',
    region: 'abdomen',
    x: 329,
    y: 439,
    city: 'Right water treatment plant',
    role: 'Filters blood and regulates fluid, electrolytes, and acid–base balance while producing urine.',
    location:
      'Retroperitoneal, on the right of the spine; usually slightly lower than the left kidney.',
    connection:
      'Urine travels down the right ureter to the bladder. Blood arrives through the right renal artery.',
    memory: 'A treatment plant recovers useful resources and sends liquid waste to storage.',
    fact: 'The liver above it contributes to the right kidney’s slightly lower position.',
    size: 21,
  },
  {
    id: 'left-kidney',
    name: 'Left kidney',
    system: 'organs',
    region: 'abdomen',
    x: 433,
    y: 431,
    city: 'Left water treatment plant',
    role: 'Filters blood and helps regulate blood pressure, fluid balance, and red blood cell production.',
    location: 'Retroperitoneal, on the left of the spine, usually higher than the right kidney.',
    connection:
      'Its renal vein drains into the inferior vena cava; its ureter carries urine to the bladder.',
    memory: 'A second treatment plant works in parallel with its partner.',
    fact: 'The kidneys sit toward the back of the abdomen, behind the peritoneal cavity.',
    size: 21,
  },
  {
    id: 'large-intestine',
    name: 'Large intestine',
    system: 'organs',
    region: 'abdomen',
    x: 380,
    y: 490,
    city: 'Water recovery & waste route',
    role: 'Absorbs water and electrolytes and forms and transports feces.',
    location:
      'Frames the small intestine, rising on the right, crossing the abdomen, and descending on the left.',
    connection: 'Receives contents from the ileum and carries them toward the rectum.',
    memory: 'A perimeter recovery route removes remaining water before waste leaves the city.',
    fact: 'The ascending and descending colon are mostly retroperitoneal.',
    size: 39,
  },
  {
    id: 'small-intestine',
    name: 'Small intestine',
    system: 'organs',
    region: 'abdomen',
    x: 381,
    y: 482,
    city: 'Nutrient market',
    role: 'Completes much of digestion and absorbs most nutrients.',
    location:
      'Coiled within the central and lower abdomen, between the stomach and large intestine.',
    connection:
      'Most absorbed nutrients enter portal blood; many dietary fats enter lymphatic lacteals.',
    memory: 'A central market distributes usable nutrients into the city’s transport networks.',
    fact: 'It has three regions: duodenum, jejunum, and ileum.',
    size: 28,
  },
  {
    id: 'bladder',
    name: 'Urinary bladder',
    system: 'organs',
    region: 'pelvis',
    x: 380,
    y: 551,
    city: 'Urine storage reservoir',
    role: 'Temporarily stores urine until it is expelled through the urethra.',
    location:
      'In the pelvis, behind the pubic symphysis. Its position and size change as it fills.',
    connection: 'Receives urine through the two ureters and empties through the urethra.',
    memory: 'A storage reservoir holds treated waste until a controlled release.',
    fact: 'The bladder stores urine; the kidneys produce it.',
    size: 26,
  },
  {
    id: 'aorta',
    name: 'Aorta',
    system: 'arteries',
    region: 'chest',
    x: 399,
    y: 338,
    city: 'Main outbound arterial route',
    role: 'Carries oxygenated blood from the left ventricle into the systemic circulation.',
    location:
      'Arches above the heart, descends through the thorax and abdomen, then divides into common iliac arteries.',
    connection: 'Major branches supply the head, arms, abdominal organs, pelvis, and legs.',
    memory: 'The main outbound route connects the pump to districts throughout the city.',
    fact: 'Arteries are named by flow away from the heart, not by oxygen content.',
    size: 20,
  },
  {
    id: 'carotid',
    name: 'Common carotid arteries',
    system: 'arteries',
    region: 'head',
    x: 402,
    y: 171,
    city: 'Head supply routes',
    role: 'Supply the head and neck through internal and external carotid branches.',
    location: 'Ascend on either side of the neck.',
    connection: 'The internal carotid arteries contribute to the brain’s blood supply.',
    memory: 'Paired northbound routes supply the command district.',
    fact: 'The brain also receives blood through the vertebral arteries.',
    size: 18,
  },
  {
    id: 'pulmonary-artery',
    name: 'Pulmonary arteries',
    system: 'arteries',
    region: 'chest',
    x: 380,
    y: 255,
    city: 'Pump-to-lung routes',
    role: 'Carry deoxygenated blood from the right ventricle to the lungs for gas exchange.',
    location: 'The pulmonary trunk divides into right and left pulmonary arteries near the heart.',
    connection:
      'Lead to the lung capillaries, where blood gains oxygen and releases carbon dioxide.',
    memory: 'A special outbound route leads to the air-exchange stations.',
    fact: 'Pulmonary arteries carry deoxygenated blood, an exception to the usual systemic color association.',
    size: 18,
  },
  {
    id: 'renal-arteries',
    name: 'Renal arteries',
    system: 'arteries',
    region: 'abdomen',
    x: 401,
    y: 442,
    city: 'Treatment-plant supply routes',
    role: 'Deliver blood to the kidneys for filtration and their own metabolic needs.',
    location: 'Branch laterally from the abdominal aorta toward each kidney.',
    connection: 'Each divides into progressively smaller arteries within the kidney.',
    memory: 'Side routes deliver blood to the two water treatment plants.',
    fact: 'The right renal artery usually passes behind the inferior vena cava.',
    size: 18,
  },
  {
    id: 'femoral-arteries',
    name: 'Femoral arteries',
    system: 'arteries',
    region: 'legs',
    x: 419,
    y: 649,
    city: 'Lower district supply routes',
    role: 'Provide a major arterial supply to the lower limbs.',
    location:
      'Continue from the external iliac arteries below the inguinal ligaments and pass through the anterior thighs.',
    connection: 'Continue as the popliteal arteries behind the knees.',
    memory: 'Major outbound routes carry supplies through the lower city.',
    fact: 'A femoral pulse can be felt just below the inguinal ligament.',
    size: 18,
  },
  {
    id: 'vena-cava',
    name: 'Venae cavae',
    system: 'veins',
    region: 'chest',
    x: 360,
    y: 340,
    city: 'Main return routes',
    role: 'Return deoxygenated blood from the systemic circulation to the right atrium.',
    location:
      'The superior vena cava serves the upper body; the inferior vena cava ascends from the abdomen.',
    connection: 'Both empty into the right atrium, completing systemic circulation.',
    memory: 'Two major return routes bring traffic back to the central pumping station.',
    fact: 'The inferior vena cava lies to the right of the abdominal aorta.',
    size: 20,
  },
  {
    id: 'jugular',
    name: 'Internal jugular veins',
    system: 'veins',
    region: 'head',
    x: 356,
    y: 169,
    city: 'Head return routes',
    role: 'Drain blood from the brain and parts of the face and neck.',
    location: 'Descend on either side of the neck within the carotid sheaths.',
    connection: 'Join the subclavian veins to form the brachiocephalic veins.',
    memory: 'Return routes bring traffic from the command district back toward the pump.',
    fact: 'Each internal jugular vein lies generally lateral to its common carotid artery.',
    size: 18,
  },
  {
    id: 'pulmonary-veins',
    name: 'Pulmonary veins',
    system: 'veins',
    region: 'chest',
    x: 422,
    y: 311,
    city: 'Lung-to-pump routes',
    role: 'Return oxygenated blood from the lungs to the left atrium.',
    location: 'Usually four veins connect the lungs to the left atrium.',
    connection: 'Complete the pulmonary circuit before the left ventricle pumps blood to the body.',
    memory: 'Freshly replenished traffic returns from the air-exchange stations.',
    fact: 'Pulmonary veins carry oxygenated blood, unlike most systemic veins.',
    size: 18,
  },
  {
    id: 'femoral-veins',
    name: 'Femoral veins',
    system: 'veins',
    region: 'legs',
    x: 336,
    y: 650,
    city: 'Lower district return routes',
    role: 'Drain the deep tissues of the lower limbs.',
    location: 'Run alongside the femoral arteries in the thighs.',
    connection: 'Continue as external iliac veins above the inguinal ligaments.',
    memory: 'Parallel return routes move lower-city traffic back toward the pump.',
    fact: 'Venous valves and muscle contractions help blood return against gravity.',
    size: 18,
  },
  {
    id: 'spinal-cord',
    name: 'Spinal cord',
    system: 'nerves',
    region: 'chest',
    x: 380,
    y: 223,
    city: 'Central communications trunk',
    role: 'Carries signals between brain and body and supports spinal reflexes.',
    location:
      'Within the vertebral canal, extending from the medulla to approximately the L1–L2 vertebral level in adults.',
    connection:
      'Spinal nerves leave through intervertebral foramina; the cauda equina continues below the cord.',
    memory: 'A protected communications trunk relays information to local networks.',
    fact: 'The adult spinal cord does not extend the full length of the vertebral column.',
    size: 18,
  },
  {
    id: 'brachial-plexus',
    name: 'Brachial plexuses',
    system: 'nerves',
    region: 'chest',
    x: 286,
    y: 234,
    city: 'Upper limb signal exchanges',
    role: 'Provide most of the motor and sensory innervation to the upper limbs.',
    location: 'Networks formed by anterior rami of C5–T1, passing from the neck into each axilla.',
    connection:
      'Give rise to major nerves including the median, ulnar, radial, musculocutaneous, and axillary nerves.',
    memory: 'Signal exchanges split a main connection into neighborhood lines.',
    fact: 'A plexus redistributes nerve fibers from several spinal levels.',
    size: 18,
  },
  {
    id: 'sciatic',
    name: 'Sciatic nerves',
    system: 'nerves',
    region: 'legs',
    x: 433,
    y: 639,
    city: 'Lower limb communications lines',
    role: 'Supply posterior thigh muscles and, through terminal branches, much of the leg and foot.',
    location: 'Run from the sacral plexuses through the buttocks and down the posterior thighs.',
    connection: 'Usually divide into tibial and common fibular nerves near the knee.',
    memory: 'Major communication lines carry instructions and feedback through the lower city.',
    fact: 'Shown schematically in this anterior view; the sciatic nerves actually run posteriorly.',
    size: 18,
  },
  {
    id: 'cervical-nodes',
    name: 'Cervical lymph nodes',
    system: 'lymph',
    region: 'head',
    x: 346,
    y: 192,
    city: 'Head & neck inspection hubs',
    role: 'Filter lymph and support immune surveillance in the head and neck.',
    location: 'Grouped throughout the neck, including chains along the internal jugular veins.',
    connection: 'Drain toward the jugular lymphatic trunks.',
    memory: 'Local inspection hubs check fluid arriving from the command district.',
    fact: 'Lymph nodes contain immune cells that respond to foreign material in lymph.',
    size: 18,
  },
  {
    id: 'axillary-nodes',
    name: 'Axillary lymph nodes',
    system: 'lymph',
    region: 'chest',
    x: 276,
    y: 272,
    city: 'Upper district inspection hubs',
    role: 'Filter lymph from much of the upper limb, breast, and superficial thoracic wall.',
    location: 'In the axillae, or armpits.',
    connection: 'Efferent vessels contribute to the subclavian lymphatic trunks.',
    memory: 'Inspection hubs sit near the routes connecting the arm districts.',
    fact: 'Lymph follows a one-way path through nodes toward the venous circulation.',
    size: 18,
  },
  {
    id: 'thoracic-duct',
    name: 'Thoracic duct',
    system: 'lymph',
    region: 'chest',
    x: 407,
    y: 230,
    city: 'Main lymph return channel',
    role: 'Returns lymph from most of the body to the venous circulation.',
    location:
      'Ascends from the abdomen through the posterior thorax and enters near the left jugular–subclavian junction.',
    connection:
      'Drains both lower limbs, abdomen, left thorax, left upper limb, and left head and neck.',
    memory: 'A collection channel returns recovered fluid to the transport network.',
    fact: 'The right upper quadrant is usually drained by the right lymphatic duct.',
    size: 18,
  },
  {
    id: 'inguinal-nodes',
    name: 'Inguinal lymph nodes',
    system: 'lymph',
    region: 'pelvis',
    x: 330,
    y: 562,
    city: 'Lower district inspection hubs',
    role: 'Filter lymph from much of the lower limbs and superficial lower trunk.',
    location: 'In the groin, with superficial and deep groups.',
    connection: 'Drain toward external iliac lymph nodes.',
    memory: 'Inspection hubs monitor the entry routes from the lower districts.',
    fact: 'Deep and superficial lymphatic vessels follow different routes toward regional nodes.',
    size: 18,
  },
];
structures.push(
  {
    id: 'upper-limb-arteries',
    name: 'Upper limb arteries',
    system: 'arteries',
    region: 'chest',
    x: 272,
    y: 316,
    city: 'Arm district supply routes',
    role: 'Carry oxygenated blood through the subclavian, axillary, brachial, radial, and ulnar arteries to the upper limbs.',
    location:
      'Run from the root of the neck through the axilla and arm; radial and ulnar branches continue through the forearm.',
    connection:
      'The right subclavian artery arises from the brachiocephalic trunk; the left arises directly from the aortic arch.',
    memory:
      'Supply routes branch into the arm districts, then divide into two main forearm routes.',
    fact: 'The radial pulse is commonly felt on the thumb side of the wrist.',
    size: 18,
  },
  {
    id: 'upper-limb-veins',
    name: 'Upper limb veins',
    system: 'veins',
    region: 'chest',
    x: 498,
    y: 355,
    city: 'Arm district return routes',
    role: 'Return blood from the hands, forearms, and arms through interconnected superficial and deep veins.',
    location:
      'Deep veins accompany arteries; superficial routes include the cephalic and basilic veins.',
    connection:
      'Blood flows toward the axillary and subclavian veins, then the brachiocephalic veins and superior vena cava.',
    memory:
      'A return network collects neighborhood traffic from the arms and brings it back toward the heart.',
    fact: 'Superficial vein patterns vary considerably between people; these routes are simplified.',
    size: 18,
  },
  {
    id: 'vagus',
    name: 'Vagus nerves',
    system: 'nerves',
    region: 'chest',
    x: 413,
    y: 351,
    city: 'Visceral regulation lines',
    role: 'Carry sensory information from many internal organs and provide parasympathetic signals to thoracic and much of the abdominal viscera.',
    location:
      'Paired cranial nerves that travel from the medulla through the neck into the thorax and abdomen.',
    connection:
      'Branches reach the heart, lungs, and digestive tract; sacral parasympathetic pathways serve more distal digestive and pelvic organs.',
    memory:
      'Regulation lines help coordinate the city’s internal services, including heart rate and digestion.',
    fact: 'The vagus nerves are cranial nerve X. Most of their fibers carry sensory information toward the brain.',
    size: 18,
  },
);
export const regions = [
  { id: 'all', name: 'Whole body' },
  { id: 'head', name: 'Head & neck' },
  { id: 'chest', name: 'Thorax' },
  { id: 'abdomen', name: 'Abdomen' },
  { id: 'pelvis', name: 'Pelvis' },
  { id: 'legs', name: 'Lower limbs' },
];
export const journeys = [
  {
    id: 'blood',
    name: 'Follow a red blood cell',
    subtitle: 'Two circuits. One continuous journey.',
    icon: 'heart',
    steps: [
      {
        id: 'vena-cava',
        text: 'Begin on the return journey. The venae cavae bring deoxygenated blood to the right atrium.',
      },
      {
        id: 'heart',
        text: 'Blood passes through the tricuspid valve into the right ventricle, then through the pulmonary valve.',
      },
      {
        id: 'pulmonary-artery',
        text: 'The pulmonary arteries carry blood away from the heart toward the lungs. This blood is low in oxygen.',
      },
      {
        id: 'right-lung',
        text: 'At lung capillaries, blood releases carbon dioxide and takes up oxygen. Both lungs participate.',
      },
      {
        id: 'pulmonary-veins',
        text: 'Pulmonary veins return oxygenated blood to the left atrium.',
      },
      {
        id: 'heart',
        text: 'Blood crosses the mitral valve into the left ventricle, then leaves through the aortic valve.',
      },
      {
        id: 'aorta',
        text: 'The aorta distributes blood to the systemic circulation. After capillary exchange, veins return it to the venae cavae.',
      },
    ],
  },
  {
    id: 'food',
    name: 'From a meal to a cell',
    subtitle: 'Trace digestion and nutrient absorption.',
    icon: 'food',
    steps: [
      {
        id: 'stomach',
        text: 'After chewing and swallowing, food reaches the stomach through the esophagus. Acid, enzymes, and muscular mixing begin processing it.',
      },
      {
        id: 'pancreas',
        text: 'Pancreatic enzymes and bicarbonate enter the duodenum to help digestion.',
      },
      {
        id: 'liver',
        text: 'The liver makes bile, which helps disperse fats into smaller droplets.',
      },
      {
        id: 'gallbladder',
        text: 'The gallbladder releases stored bile through the biliary ducts into the duodenum.',
      },
      {
        id: 'small-intestine',
        text: 'Most nutrients are absorbed here. Sugars and amino acids enter portal blood; many fats enter lymphatic lacteals.',
      },
      {
        id: 'large-intestine',
        text: 'Remaining material enters the colon, where water and electrolytes are absorbed before waste passes toward the rectum.',
      },
    ],
  },
  {
    id: 'lymph',
    name: 'The fluid return journey',
    subtitle: 'Discover the body’s recovery network.',
    icon: 'lymph',
    steps: [
      {
        id: 'inguinal-nodes',
        text: 'Excess interstitial fluid enters lymphatic capillaries. Much of the lower limb’s lymph passes through inguinal nodes.',
      },
      {
        id: 'thoracic-duct',
        text: 'After deeper nodes and lymphatic trunks, lymph from the lower body enters the thoracic duct, often through the cisterna chyli.',
      },
      {
        id: 'jugular',
        text: 'The thoracic duct empties near the junction of the left internal jugular and subclavian veins, returning fluid to blood.',
      },
      {
        id: 'vena-cava',
        text: 'Returned fluid travels with venous blood through the left brachiocephalic vein into the superior vena cava and then the right atrium.',
      },
    ],
  },
];
journeys.push({
  id: 'signal',
  name: 'Trace a sensory signal',
  subtitle: 'From a step to a conscious sensation.',
  icon: 'nerves',
  steps: [
    {
      id: 'sciatic',
      text: 'Signals from receptors in the foot travel in peripheral nerves. Many pass through tibial or common fibular fibers within the sciatic nerve.',
    },
    {
      id: 'spinal-cord',
      text: 'Sensory fibers enter the spinal cord through dorsal roots. Ascending pathways carry information toward the brain; some signals also drive local reflex circuits.',
    },
    {
      id: 'brain',
      text: 'After relays—including the thalamus for conscious body sensation—the cerebral cortex interprets the information. Different sensory modalities use different pathways.',
    },
  ],
});
export const quizQuestions = [
  {
    question: 'Which structure is the city’s central pumping station?',
    answer: 'heart',
    options: ['liver', 'heart', 'brain', 'bladder'],
    why: 'The heart drives the pulmonary and systemic circulations with its right and left pumps.',
  },
  {
    question:
      'In an anterior view, which organ is mainly on the viewer’s left, beneath the diaphragm?',
    answer: 'liver',
    options: ['stomach', 'spleen', 'liver', 'left-kidney'],
    why: 'The viewer’s left is the patient’s right. The liver lies mainly in the right upper abdomen.',
  },
  {
    question: 'Which vessels carry deoxygenated blood away from the heart?',
    answer: 'pulmonary-artery',
    options: ['aorta', 'pulmonary-veins', 'pulmonary-artery', 'vena-cava'],
    why: 'Pulmonary arteries carry deoxygenated blood to the lungs. Arteries are defined by direction of flow.',
  },
  {
    question: 'Where are most nutrients absorbed?',
    answer: 'small-intestine',
    options: ['stomach', 'large-intestine', 'liver', 'small-intestine'],
    why: 'The small intestine’s folds, villi, and microvilli provide a large surface for absorption.',
  },
  {
    question: 'Which structure returns lymph from most of the body to the venous circulation?',
    answer: 'thoracic-duct',
    options: ['aorta', 'thoracic-duct', 'spinal-cord', 'spleen'],
    why: 'The thoracic duct drains most of the body into the venous system near the left venous angle.',
  },
  {
    question: 'Which organ is usually slightly lower than its partner?',
    answer: 'right-kidney',
    options: ['left-kidney', 'right-kidney', 'left-lung', 'thyroid'],
    why: 'The liver above the right kidney contributes to its slightly lower position.',
  },
  {
    question: 'Which network supplies most motor and sensory innervation to the upper limbs?',
    answer: 'brachial-plexus',
    options: ['sciatic', 'spinal-cord', 'brachial-plexus', 'cervical-nodes'],
    why: 'The brachial plexuses redistribute fibers from C5–T1 to the major nerves of the upper limbs.',
  },
];
